// 
// Animation(QtQuick)
//      property:
//          loops: int
//          running: bool
//          paused: bool
//          alwaysRunToEnd: bool
//      signal:
//          started()
//          stopped()
//          finished()
//      method;
//          start()
//          stop()
//          pause()
//          resume()
//          restart()
//          complete()
// Easing.type:
//      Easing.Linear
//      Easing.InQuad
//      Easing.OutQuad
//      Easing.InOutQuad
//      Easing.OutInQuad
//      Easing.InCubic
//      Easing.OutCubic
//      Easing.InOutCubic
//      Easing.OutInCubic
//      Easing.InQuart
//      Easing.OutQuart
//      Easing.InOutQuart
//      Easing.OutInQuart
//      Easing.InQuint
//      Easing.OutQuint
//      Easing.InOutQuint
//      Easing.OutInQuint
//      Easing.InSine
//      Easing.OutSine
//      Easing.InOutSine
//      Easing.OutInSine
//      Easing.InExpo
//      Easing.OutExpo
//      Easing.InOutExpo
//      Easing.OutInExpo
//      Easing.InCirc
//      Easing.OutCirc
//      Easing.InOutCirc
//      Easing.OutInCirc
//      Easing.InElastic
//      Easing.OutElastic
//      Easing.InOutElastic
//      Easing.OutInElastic
//      Easing.InBack
//      Easing.OutBack
//      Easing.InOutBack
//      Easing.OutInBack
//      Easing.InBounce
//      Easing.OutBounce
//      Easing.InOutBounce
//      Easing.OutInBounce
//      Easing.BezierSpline